refactor
iamfreeCodeCamp/iamfreecodecamp pull request #28
Opened 2021-11-19 19:22 UTC by varun-tiwari

added reddit icon to header and  footer

2021-11-20 14:08 UTC, evedes requested changes
Hey, good job with the reddit icon! 
Left only a small comment about using colors in tailwind.

Also, we're using yarn, so we don't need a package-lock.json in our codebase. Could you remove it? 

Thanks! And keep up the good work! ❤️

2021-11-20 14:08 UTC, evedes commented on components/Header/Header.js
> +          <FaReddit className="w-6 h-6 sm:w-8 sm:h-8 hover:text-reddit-200 text-reddit-100 transition duration-300 ease-in-out" />
I've seen you used text-reddit-100 and text-reddit-200. For this to work you need to add the reddit color in the tailwind.config.js. I'd suggest to use orange as the default color, so we need two shades of orange, one lighter and one darker, just like in the twitter case.

2021-11-27 16:15 UTC, evedes commented on components/Header/Header.js
> +          <FaReddit className="w-6 h-6 sm:w-8 sm:h-8 hover:text-reddit-200 text-reddit-100 transition duration-300 ease-in-out" />
Hey @varun-tiwari, are you going to finish this or can we move the ticket to someone else? 🙏🏻

2021-11-27 18:49 UTC, varun-tiwari commented
@evedes  Hi Evedes, sorry for delay, could you please review my new commit,please let me know if any other changes neede.

2021-11-28 16:17 UTC, evedes commented
Great job @varun-tiwari! ❤️  We're really thankful for your contribution!

2021-11-28 16:29 UTC, evedes commented
@varun-tiwari your code is approved, but there are conflicts to solve. Reach out on Discord if you need help solving them! #contributors channel 👍🏻

2021-12-03 02:26 UTC, evedes commented
I ended up giving you a hand mate! Good job anyway! ❤️ 
Merged here: https://github.com/iamfreeCodeCamp/iamfreecodecamp/pull/33
Closing the PR.

2021-12-03 02:26 UTC, closed without merging